"""Mission — Daily community news post (Plan CEO V9 / mission 3).

Every day at 09:00 local time, posts a short update in the MAXIA
Community Discord server (#announcements channel) via the MAXIA
outreach bot that is already a member of the server.

Content generated by qwen3.5:27b with live data pulled from the VPS
public endpoints (already verified in capabilities_prod.json):

    /api/public/crypto/prices   -> top 5 token prices
    /api/public/marketplace-stats -> MAXIA activity
    /oracle/monitoring          -> oracle latency

Post format (English, short):
    [Topic] + [1 live stat] + [link to maxiaworld.app]

Rate limiting:
- Exactly 1 post per day at 09:00 UTC
- Post is sent via the same ``_default_discord_send`` used by
  ``backend/marketing/discord_outreach.py`` — no new dependency.
- Falls back to a deterministic template if Qwen or oracle call fails.
"""
from __future__ import annotations

import json
import logging
import os
import sys
from datetime import datetime
from typing import Optional

log = logging.getLogger("ceo")

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)
)))
_BACKEND_DIR = os.path.join(_REPO_ROOT, "backend")
# IMPORTANT: append (not insert) so ``backend/agents/`` package does NOT
# shadow ``local_ceo/agents.py``. The only import we need from backend is
# ``marketing.discord_outreach`` which is unique to backend, so being at
# the tail of sys.path is enough.
if _BACKEND_DIR not in sys.path:
    sys.path.append(_BACKEND_DIR)

OUTREACH_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "memory_prod", "outreach_channels.json",
)

DAILY_HOUR: int = 9                     # local time
POST_MAX_CHARS: int = 1000


def _load_announcements_channel() -> Optional[tuple[str, str, str]]:
    """Return (guild_name, guild_id, announcements_channel_id) from memory_prod."""
    try:
        with open(OUTREACH_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError) as e:
        log.warning("[community_news] cannot read outreach_channels.json: %s", e)
        return None

    community = (
        data.get("channels", {})
        .get("discord_ceo", {})
        .get("community_server", {})
    )
    guild_name = community.get("name", "") or community.get("guild_name", "")
    guild_id = community.get("guild_id", "")
    channels = community.get("channels", {}) or {}
    channel_id = channels.get("announcements") or channels.get("general")
    if not guild_id or not channel_id:
        return None
    return guild_name, guild_id, channel_id


async def _fetch_live_stats() -> dict:
    """Pull a few live numbers from the VPS to ground the LLM generation."""
    stats: dict = {"prices": {}, "marketplace": {}, "oracle": {}}
    try:
        import httpx
        from config_local import VPS_URL
    except ImportError:
        return stats

    async with httpx.AsyncClient(timeout=10) as client:
        for label, path in (
            ("prices", "/api/public/crypto/prices"),
            ("marketplace", "/api/public/marketplace-stats"),
            ("oracle", "/oracle/monitoring"),
        ):
            try:
                resp = await client.get(f"{VPS_URL}{path}")
                if resp.status_code == 200:
                    payload = resp.json()
                    if isinstance(payload, dict):
                        stats[label] = payload
            except Exception as e:
                log.debug("[community_news] %s fetch failed: %s", path, e)
    return stats


async def _generate_post_text(stats: dict) -> str:
    """Ask qwen3.5:27b for a short daily update. Fallback if LLM fails."""
    default = (
        "**MAXIA daily update**\n\n"
        "AI-to-AI marketplace on 15 blockchains. 46 MCP tools, GPU rental "
        "via Akash, 65-token multi-chain swap via Jupiter and 0x.\n\n"
        "Paper trading by default. https://maxiaworld.app"
    )

    try:
        from llm import ask
        from agents import WRITER
    except ImportError:
        return default

    prices_blob = ""
    prices = stats.get("prices") or {}
    if isinstance(prices, dict):
        items = list(prices.items())[:5]
        prices_blob = "\n".join(f"- {k}: {v}" for k, v in items)

    prompt = (
        "Write a SHORT Discord announcement (max 600 characters) for the "
        "MAXIA Community server. Topic: MAXIA AI-to-AI marketplace on 15 "
        "blockchains, 46 MCP tools, GPU rental via Akash, token swap via "
        "Jupiter and 0x. Mention 'paper trading by default'. Include the "
        "link https://maxiaworld.app at the end. English only. No emoji. "
        "No markdown except **bold** for the title. Include one live fact "
        "from these prices if available:\n\n"
        f"{prices_blob}\n\n"
        "Output only the final message, nothing else."
    )

    try:
        response = await ask(WRITER, prompt)
    except Exception as e:
        log.warning("[community_news] LLM error, using fallback: %s", e)
        return default

    if not isinstance(response, str) or len(response) < 30:
        return default

    # Trim to Discord safe length
    text = response.strip()[:POST_MAX_CHARS]
    return text


async def _send_to_discord(channel_id: str, content: str) -> bool:
    """Send content to Discord via the backend helper."""
    try:
        from marketing.discord_outreach import _default_discord_send
    except ImportError as e:
        log.warning("[community_news] discord sender unavailable: %s", e)
        return False

    try:
        await _default_discord_send(
            server_id="community",
            channel_id=channel_id,
            content=content,
        )
        return True
    except Exception as e:
        log.error("[community_news] discord send failed: %s", e)
        return False


async def _request_orange_approval(
    content: str,
    guild_name: str,
    guild_id: str,
    channel_id: str,
) -> str:
    """Send a GO/NO approval request and wait via the shared telegram_router.

    The router is the single Telegram long-poller for the whole local CEO.
    We only send the message + edit it with the final verdict; the router
    dispatches the callback_query to our waiter.
    """
    import httpx
    from config_local import (
        APPROVAL_TIMEOUT_ORANGE_S,
        TELEGRAM_BOT_TOKEN,
        TELEGRAM_CEO_CHAT_ID,
    )
    from telegram_router import await_approval

    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CEO_CHAT_ID:
        log.warning("[community_news] Telegram not configured — skip approval")
        return "timeout"

    action_id = f"community_news_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    api_base = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}"

    preview = content[:900]
    server_label = guild_name or f"guild {guild_id}"
    text = (
        f"\U0001f7e0 *ORANGE* — Post daily community news\n\n"
        f"*Serveur:* {server_label} (`{guild_id}`)\n"
        f"*Channel:* `#announcements` (`{channel_id}`)\n"
        f"*Longueur:* {len(content)} chars\n\n"
        f"*Draft:*\n```\n{preview}\n```\n\n"
        f"Approuver ce post Discord ?"
    )
    keyboard = {
        "inline_keyboard": [[
            {"text": "\u2705 GO", "callback_data": f"approve:{action_id}"},
            {"text": "\u274c NO", "callback_data": f"reject:{action_id}"},
        ]]
    }

    message_id: Optional[int] = None
    async with httpx.AsyncClient(timeout=15) as client:
        try:
            resp = await client.post(
                f"{api_base}/sendMessage",
                json={
                    "chat_id": TELEGRAM_CEO_CHAT_ID,
                    "text": text,
                    "parse_mode": "Markdown",
                    "reply_markup": keyboard,
                },
            )
            if resp.status_code != 200:
                log.warning("[community_news] Telegram sendMessage HTTP %s: %s",
                            resp.status_code, resp.text[:200])
                return "timeout"
            try:
                message_id = int(resp.json().get("result", {}).get("message_id", 0)) or None
            except Exception:
                message_id = None
        except Exception as e:
            log.warning("[community_news] Telegram send error: %s", e)
            return "timeout"

        verdict = await await_approval(action_id, APPROVAL_TIMEOUT_ORANGE_S)

        if message_id:
            stamp = datetime.now().strftime("%H:%M:%S")
            if verdict == "human":
                banner = f"\u2705 *APPROUVE a {stamp}*"
            elif verdict == "denied":
                banner = f"\u274c *REFUSE a {stamp}*"
            else:
                banner = f"\u23f1 *TIMEOUT a {stamp}*"
            new_text = f"{banner}\n\n{text}"
            if len(new_text) > 4000:
                new_text = new_text[:4000] + "..."
            try:
                await client.post(
                    f"{api_base}/editMessageText",
                    json={
                        "chat_id": TELEGRAM_CEO_CHAT_ID,
                        "message_id": message_id,
                        "text": new_text,
                        "parse_mode": "Markdown",
                    },
                    timeout=10,
                )
            except Exception as e:
                log.debug("[community_news] editMessageText failed: %s", e)

    return verdict


async def mission_community_news(
    mem: dict,
    actions: dict,
    *,
    force: bool = False,
) -> None:
    """Post daily community news in MAXIA Community #announcements.

    Flow:
      1. Fetch live stats (prices, marketplace, oracle).
      2. Ask WRITER LLM for a short Discord-safe post.
      3. Send GO/NO approval request to Alexis on Telegram (ORANGE).
      4. If approved → POST to Discord, else log and skip.

    Args:
        mem: persistent memory dict (daily dedupe, post history).
        actions: daily counters.
        force: if ``True``, bypass hour + daily-dedupe checks. Used by
            ``test_community_news_now.py`` to trigger a one-shot test.
    """
    today = datetime.now().strftime("%Y-%m-%d")
    if not force:
        if mem.get("_community_news_last_date") == today:
            return
        if datetime.now().hour != DAILY_HOUR:
            return

    channel = _load_announcements_channel()
    if channel is None:
        log.warning("[community_news] no announcements channel info — skip")
        return
    guild_name, guild_id, channel_id = channel

    stats = await _fetch_live_stats()
    content = await _generate_post_text(stats)
    log.info("[community_news] draft ready (%d chars), requesting approval", len(content))

    verdict = await _request_orange_approval(content, guild_name, guild_id, channel_id)

    # Dedupe immediately after verdict, regardless of outcome. "We tried
    # today, don't retry until tomorrow." Without this, denied/timeout
    # fell through without setting the flag and the mission refired every
    # scheduler loop (~1 min) for the rest of hour 9, flooding Telegram.
    mem["_community_news_last_date"] = today

    try:
        from memory import log_action
        log_action(
            "community_news_approval",
            target=verdict,
            details=f"{guild_name}#announcements draft {len(content)} chars",
        )
    except Exception as _e:
        log.debug("[community_news] log_action verdict failed: %s", _e)

    if verdict == "denied":
        log.info("[community_news] DENIED by Alexis — skip post")
        return
    if verdict == "timeout":
        log.warning("[community_news] approval TIMEOUT — skip post (no auto-publish)")
        return
    # "human" (approved) or "auto" (vert, shouldn't happen here) → publish
    log.info("[community_news] approved (%s) — posting to Discord", verdict)

    ok = await _send_to_discord(channel_id, content)
    if not ok:
        return

    mem.setdefault("community_news_posts", []).append({
        "date": today,
        "channel_id": channel_id,
        "guild_id": guild_id,
        "length": len(content),
    })
    if len(mem["community_news_posts"]) > 200:
        mem["community_news_posts"] = mem["community_news_posts"][-200:]
    try:
        from memory import log_action
        log_action(
            "community_news_posted",
            target=f"{guild_name}#announcements",
            details=f"posted {len(content)} chars to channel {channel_id}",
        )
    except Exception as _e:
        log.debug("[community_news] log_action posted failed: %s", _e)

    actions["counts"]["community_news"] = 1
    log.info("[community_news] posted daily update (%d chars)", len(content))
