"""Mission — Daily community news post (Plan CEO V9 / mission 3).

Every day at 09:00 local time, posts a short update in the MAXIA
Community Discord server (#announcements channel) via the MAXIA
outreach bot that is already a member of the server.

Content generated by qwen3.5:27b with live data pulled from the VPS
public endpoints (already verified in capabilities_prod.json):

    /api/public/crypto/prices   -> top 5 token prices
    /api/public/marketplace-stats -> MAXIA activity
    /oracle/monitoring          -> oracle latency

Post format (English, short):
    [Topic] + [1 live stat] + [link to maxiaworld.app]

Rate limiting:
- Exactly 1 post per day at 09:00 UTC
- Post is sent via the same ``_default_discord_send`` used by
  ``backend/marketing/discord_outreach.py`` — no new dependency.
- Falls back to a deterministic template if Qwen or oracle call fails.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
from datetime import datetime
from typing import Optional

log = logging.getLogger("ceo")

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)
)))
_BACKEND_DIR = os.path.join(_REPO_ROOT, "backend")
if _BACKEND_DIR not in sys.path:
    sys.path.insert(0, _BACKEND_DIR)

OUTREACH_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "memory_prod", "outreach_channels.json",
)

DAILY_HOUR: int = 9                     # local time
POST_MAX_CHARS: int = 1000


def _load_announcements_channel() -> Optional[tuple[str, str]]:
    """Return (guild_id, announcements_channel_id) from memory_prod."""
    try:
        with open(OUTREACH_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError) as e:
        log.warning("[community_news] cannot read outreach_channels.json: %s", e)
        return None

    community = (
        data.get("channels", {})
        .get("discord_ceo", {})
        .get("community_server", {})
    )
    guild_id = community.get("guild_id", "")
    channels = community.get("channels", {}) or {}
    channel_id = channels.get("announcements") or channels.get("general")
    if not guild_id or not channel_id:
        return None
    return guild_id, channel_id


async def _fetch_live_stats() -> dict:
    """Pull a few live numbers from the VPS to ground the LLM generation."""
    stats: dict = {"prices": {}, "marketplace": {}, "oracle": {}}
    try:
        import httpx
        from config_local import VPS_URL
    except ImportError:
        return stats

    async with httpx.AsyncClient(timeout=10) as client:
        for label, path in (
            ("prices", "/api/public/crypto/prices"),
            ("marketplace", "/api/public/marketplace-stats"),
            ("oracle", "/oracle/monitoring"),
        ):
            try:
                resp = await client.get(f"{VPS_URL}{path}")
                if resp.status_code == 200:
                    payload = resp.json()
                    if isinstance(payload, dict):
                        stats[label] = payload
            except Exception as e:
                log.debug("[community_news] %s fetch failed: %s", path, e)
    return stats


async def _generate_post_text(stats: dict) -> str:
    """Ask qwen3.5:27b for a short daily update. Fallback if LLM fails."""
    default = (
        "**MAXIA daily update**\n\n"
        "AI-to-AI marketplace on 15 blockchains. 46 MCP tools, GPU rental "
        "via Akash, 65-token multi-chain swap via Jupiter and 0x.\n\n"
        "Paper trading by default. https://maxiaworld.app"
    )

    try:
        from llm import ask
        from agents import WRITER
    except ImportError:
        return default

    prices_blob = ""
    prices = stats.get("prices") or {}
    if isinstance(prices, dict):
        items = list(prices.items())[:5]
        prices_blob = "\n".join(f"- {k}: {v}" for k, v in items)

    prompt = (
        "Write a SHORT Discord announcement (max 600 characters) for the "
        "MAXIA Community server. Topic: MAXIA AI-to-AI marketplace on 15 "
        "blockchains, 46 MCP tools, GPU rental via Akash, token swap via "
        "Jupiter and 0x. Mention 'paper trading by default'. Include the "
        "link https://maxiaworld.app at the end. English only. No emoji. "
        "No markdown except **bold** for the title. Include one live fact "
        "from these prices if available:\n\n"
        f"{prices_blob}\n\n"
        "Output only the final message, nothing else."
    )

    try:
        response = await ask(WRITER, prompt)
    except Exception as e:
        log.warning("[community_news] LLM error, using fallback: %s", e)
        return default

    if not isinstance(response, str) or len(response) < 30:
        return default

    # Trim to Discord safe length
    text = response.strip()[:POST_MAX_CHARS]
    return text


async def _send_to_discord(channel_id: str, content: str) -> bool:
    """Send content to Discord via the backend helper."""
    try:
        from marketing.discord_outreach import _default_discord_send
    except ImportError as e:
        log.warning("[community_news] discord sender unavailable: %s", e)
        return False

    try:
        await _default_discord_send(
            server_id="community",
            channel_id=channel_id,
            content=content,
        )
        return True
    except Exception as e:
        log.error("[community_news] discord send failed: %s", e)
        return False


async def mission_community_news(mem: dict, actions: dict) -> None:
    """Post daily community news in MAXIA Community #announcements."""
    today = datetime.now().strftime("%Y-%m-%d")
    if mem.get("_community_news_last_date") == today:
        return
    if datetime.now().hour != DAILY_HOUR:
        return

    channel = _load_announcements_channel()
    if channel is None:
        log.warning("[community_news] no announcements channel info — skip")
        return
    guild_id, channel_id = channel

    stats = await _fetch_live_stats()
    content = await _generate_post_text(stats)

    ok = await _send_to_discord(channel_id, content)
    if not ok:
        return

    mem["_community_news_last_date"] = today
    mem.setdefault("community_news_posts", []).append({
        "date": today,
        "channel_id": channel_id,
        "guild_id": guild_id,
        "length": len(content),
    })
    if len(mem["community_news_posts"]) > 200:
        mem["community_news_posts"] = mem["community_news_posts"][-200:]

    actions["counts"]["community_news"] = 1
    log.info("[community_news] posted daily update (%d chars)", len(content))
