"""Mission — Weekly CEO report (Plan CEO V9 / mission 5).

Every Monday at 09:00 local time, assembles a plain-text weekly report
and sends it to Alexis at ``ceo@maxiaworld.app`` via the existing
``scheduler.send_mail`` helper.

Report contents:
- Week number + date range
- Disboard bumps sent (from mem["disboard_bumps"])
- GitHub prospects sent (from mem["github_prospects"])
- Blog cross-posts published (from mem["blog_crossposts_log"])
- Community news posts (from mem["community_news_posts"])
- Health checks (from mem["health_checks"])
- Top 3 Reddit mentions of the week (from mem["reddit_mentions"])
- Narrative summary generated by qwen3.5:27b from the above

The whole pipeline is defensive: any missing key in mem just becomes
"0" in the counts. A missing LLM or Ollama simply emails the raw
counts without the narrative.
"""
from __future__ import annotations

import logging
import time
from datetime import datetime, timedelta
from typing import Optional

log = logging.getLogger("ceo")

REPORT_HOUR: int = 9
REPORT_WEEKDAY: int = 0   # Monday


def _week_window(now: datetime) -> tuple[datetime, datetime, str]:
    start = now - timedelta(days=7)
    label = f"{start.strftime('%Y-%m-%d')} -> {now.strftime('%Y-%m-%d')}"
    return start, now, label


def _count_since(items: list, key: str, start_ts: float) -> int:
    count = 0
    for item in items:
        if not isinstance(item, dict):
            continue
        ts = item.get(key)
        if isinstance(ts, (int, float)) and ts >= start_ts:
            count += 1
        elif isinstance(ts, str):
            try:
                if datetime.fromisoformat(ts).timestamp() >= start_ts:
                    count += 1
            except ValueError:
                pass
    return count


def _assemble_counts(mem: dict, start_ts: float) -> dict[str, int]:
    return {
        "disboard_bumps": _count_since(mem.get("disboard_bumps", []), "ts", start_ts),
        "github_prospects_sent": _count_since(
            mem.get("github_prospects", []), "ts", start_ts,
        ),
        "blog_crossposts": len([
            p for p in mem.get("blog_crossposts_log", [])
            if isinstance(p, dict) and p.get("date", "") >= (
                datetime.fromtimestamp(start_ts).strftime("%Y-%m-%d")
            )
        ]),
        "community_news_posts": len([
            p for p in mem.get("community_news_posts", [])
            if isinstance(p, dict) and p.get("date", "") >= (
                datetime.fromtimestamp(start_ts).strftime("%Y-%m-%d")
            )
        ]),
        "health_alerts": len(mem.get("health_alerts", [])[-50:]),
        "reddit_mentions_total": len(mem.get("reddit_mentions", [])[-100:]),
    }


def _sales_section() -> str:
    """Best-effort snapshot of MaxiaSalesAgent metrics for the report.

    Returns an empty string if the sales DB is missing or the dashboard
    helper cannot be imported (so the weekly report still works on a
    machine where the sales agent is not deployed yet).
    """
    try:
        from sales.dashboard import snapshot, format_text
    except ImportError:
        return ""
    try:
        metrics = snapshot()
    except Exception as e:
        log.debug("[weekly_report] sales snapshot failed: %s", e)
        return ""
    if not metrics.get("ok"):
        return ""
    text = format_text(metrics)
    # Strip the dashboard header so it blends into the email
    return text.replace("=" * 64, "").strip()


def _assemble_body(counts: dict[str, int], label: str, narrative: str) -> str:
    lines = [
        f"MAXIA CEO — Weekly report",
        f"Week: {label}",
        "",
        "Automated actions (last 7 days)",
        f"  DISBOARD bump reminders sent : {counts['disboard_bumps']}",
        f"  GitHub prospects emailed     : {counts['github_prospects_sent']}",
        f"  Blog cross-posts published   : {counts['blog_crossposts']}",
        f"  Community news posts         : {counts['community_news_posts']}",
        f"  Health alerts (recent total) : {counts['health_alerts']}",
        f"  Reddit mentions tracked      : {counts['reddit_mentions_total']}",
        "",
    ]

    sales_text = _sales_section()
    if sales_text:
        lines.append("MaxiaSalesAgent (sales conversations)")
        lines.append(sales_text)
        lines.append("")

    if narrative:
        lines.append("Narrative")
        lines.append(narrative.strip())
        lines.append("")
    lines.append("---")
    lines.append("Generated by CEO local V9 on qwen3:30b-a3b-instruct-2507")
    return "\n".join(lines)


async def _generate_narrative(counts: dict[str, int], label: str) -> str:
    """Ask qwen3.5:27b for a short weekly summary. Falls back to empty."""
    try:
        from llm import ask
        from agents import WRITER
    except ImportError:
        return ""

    prompt = (
        "You are MAXIA CEO reporting to Alexis. Write a SHORT (max 120 words) "
        "weekly summary in English based ONLY on these numbers:\n\n"
        f"Week: {label}\n"
        f"DISBOARD bump reminders: {counts['disboard_bumps']}\n"
        f"GitHub prospects emailed: {counts['github_prospects_sent']}\n"
        f"Blog cross-posts published: {counts['blog_crossposts']}\n"
        f"Community news posts: {counts['community_news_posts']}\n"
        f"Health alerts recent: {counts['health_alerts']}\n"
        f"Reddit mentions tracked: {counts['reddit_mentions_total']}\n\n"
        "Rules:\n"
        "- Plain text only, no markdown, no emoji\n"
        "- 3-4 short paragraphs max\n"
        "- Flag anything that needs Alexis attention\n"
        "- If all numbers are 0, suggest concrete next steps\n"
    )
    try:
        out = await ask(WRITER, prompt)
        if isinstance(out, str) and 50 < len(out) < 3000:
            return out.strip()
    except Exception as e:
        log.warning("[weekly_report] LLM narrative failed: %s", e)
    return ""


async def mission_weekly_report(mem: dict, actions: dict) -> None:
    """Generate + email the weekly report every Monday at 09h local."""
    now = datetime.now()
    today_str = now.strftime("%Y-%m-%d")

    if mem.get("_weekly_report_last_date") == today_str:
        return
    if now.weekday() != REPORT_WEEKDAY or now.hour != REPORT_HOUR:
        return

    start, end, label = _week_window(now)
    counts = _assemble_counts(mem, start.timestamp())
    narrative = await _generate_narrative(counts, label)
    body = _assemble_body(counts, label, narrative)

    try:
        from scheduler import send_mail
    except ImportError as e:
        log.error("[weekly_report] send_mail unavailable: %s", e)
        return

    subject = f"[MAXIA CEO] Weekly report {label}"
    try:
        await send_mail(subject, body)
    except Exception as e:
        log.error("[weekly_report] send_mail failed: %s", e)
        return

    mem["_weekly_report_last_date"] = today_str
    mem.setdefault("weekly_reports", []).append({
        "date": today_str,
        "label": label,
        "counts": counts,
        "ts": int(time.time()),
    })
    if len(mem["weekly_reports"]) > 52:
        mem["weekly_reports"] = mem["weekly_reports"][-52:]

    actions["counts"]["weekly_report"] = 1
    log.info("[weekly_report] sent for %s", label)
    try:
        from memory import log_action
        log_action(
            "weekly_report_sent",
            target="alexis@email",
            details=f"week {label}",
        )
    except Exception as _e:
        log.debug("[weekly_report] log_action failed: %s", _e)
