[features]
seeds = false
skip-lint = false

[programs.mainnet]
maxia_escrow = "8ADNmAPDxuRvJPBp8dL9rq5jpcGtqAEx4JyZd1rXwBUY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'No tests configured'"
